### ISSUE TITLE
Open Support Group In Telegram...

### ISSUE THREAD

**Issue by AminSiddika** [TeamKillerX/Akeno-Userbot#32]
**you Guys Should Open Support Group On Telegram...**
For Linux Based Server Guide Proper Introduction....
It's pain in butt....

**Comment by xtsea** [comment]
> **you Guys Should Open Support Group On Telegram...** For Linux Based Server Guide Proper Introduction.... It's pain in butt....

Choose a Linux distribution (e.g., Ubuntu, Debian)

**Comment by xtsea** [comment]
Read on readme.md

**Comment by AminSiddika** [comment]
> Read on readme.md

I read it but version not specified...
in ubuntu 22 python3.10 version have some issue with av==8.0.1 
In Ubuntu 24 python3.12 have some issue with pytgcalls 😆😆...
That's specified version should be mentioned...
And docker isn't work...
env missing...

**Comment by xtsea** [comment]
> > Read on readme.md
> 
> I read it but version not specified... in ubuntu 22 python3.10 version have some issue with av==8.0.1 In Ubuntu 24 python3.12 have some issue with pytgcalls 😆😆... That's why specified version should be mentioned... And docker isn't work... env missing...

type "git pull" please update first
