### ISSUE TITLE
Error On Pytgcalls Via Docker Run...

### ISSUE THREAD

**Issue by AminSiddika** [TeamKillerX/Akeno-Userbot#33]
` INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/Akeno/__init__.py", line 23, in <module>
    from pytgcalls import GroupCallFactory
ModuleNotFoundError: No module named 'pytgcalls' `

**Docker**

python : 3.12.4
ubuntu : 24

**Comment by xtsea** [comment]
> `INFO: Started server process [7] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit) Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details __import__(pkg_name) File "/usr/src/app/Akeno/__init__.py", line 23, in <module> from pytgcalls import GroupCallFactory ModuleNotFoundError: No module named 'pytgcalls'`
> 
> **Docker**
> 
> python : 3.12.4 ubuntu : 24

install pytgcalls first

**Comment by AminSiddika** [comment]
`Collecting pytgcalls
  Using cached pytgcalls-2.1.0-py3-none-any.whl.metadata (12 kB)
INFO: pip is looking at multiple versions of pytgcalls to determine which version is compatible with other requirements. This could take a while.
  Using cached pytgcalls-2.0.0-py3-none-any.whl.metadata (11 kB)
  Using cached pytgcalls-1.0.0-py3-none-any.whl.metadata (11 kB)
  Using cached pytgcalls-0.0.24-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.23-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.22-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.21-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.19-py3-none-any.whl.metadata (9.6 kB)
INFO: pip is still looking at multiple versions of pytgcalls to determine which version is compatible with other requirements. This could
take a while.
  Using cached pytgcalls-0.0.18-py3-none-any.whl.metadata (9.6 kB)
  Using cached pytgcalls-0.0.17-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.16-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.15-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.14-py3-none-any.whl.metadata (8.8 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want
to abort this run, press Ctrl + C.
  Using cached pytgcalls-0.0.13-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.12-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.11-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.10-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.9-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.8-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.7-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.6-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.5-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.4-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.3-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.2-py3-none-any.whl.metadata (8.6 kB)
ERROR: Cannot install pytgcalls==0.0.10, pytgcalls==0.0.11, pytgcalls==0.0.12, pytgcalls==0.0.13, pytgcalls==0.0.14, pytgcalls==0.0.15, pytgcalls==0.0.16, pytgcalls==0.0.17, pytgcalls==0.0.18, pytgcalls==0.0.19, pytgcalls==0.0.2, pytgcalls==0.0.21, pytgcalls==0.0.22, pytgcalls==0.0.23, pytgcalls==0.0.24, pytgcalls==0.0.3, pytgcalls==0.0.4, pytgcalls==0.0.5, pytgcalls==0.0.6, pytgcalls==0.0.7, pytgcalls==0.0.8, pytgcalls==0.0.9, pytgcalls==1.0.0, pytgcalls==2.0.0 and pytgcalls==2.1.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    pytgcalls 2.1.0 depends on tgcalls==2.0.0
    pytgcalls 2.0.0 depends on tgcalls==2.0.0
    pytgcalls 1.0.0 depends on tgcalls==1.0.0
    pytgcalls 0.0.24 depends on tgcalls==0.0.16
    pytgcalls 0.0.23 depends on tgcalls==0.0.16
    pytgcalls 0.0.22 depends on tgcalls==0.0.15
    pytgcalls 0.0.21 depends on tgcalls==0.0.14
    pytgcalls 0.0.19 depends on tgcalls==0.0.12
    pytgcalls 0.0.18 depends on tgcalls==0.0.12
    pytgcalls 0.0.17 depends on tgcalls==0.0.11
    pytgcalls 0.0.16 depends on tgcalls==0.0.10
    pytgcalls 0.0.15 depends on tgcalls==0.0.10
    pytgcalls 0.0.14 depends on tgcalls==0.0.10
    pytgcalls 0.0.13 depends on tgcalls==0.0.9
    pytgcalls 0.0.12 depends on tgcalls==0.0.8
    pytgcalls 0.0.11 depends on tgcalls==0.0.7
    pytgcalls 0.0.10 depends on tgcalls==0.0.6
    pytgcalls 0.0.9 depends on tgcalls==0.0.5
    pytgcalls 0.0.8 depends on tgcalls==0.0.4
    pytgcalls 0.0.7 depends on tgcalls==0.0.4
    pytgcalls 0.0.6 depends on tgcalls==0.0.4
    pytgcalls 0.0.5 depends on tgcalls==0.0.3
    pytgcalls 0.0.4 depends on tgcalls==0.0.3
    pytgcalls 0.0.3 depends on tgcalls==0.0.3
    pytgcalls 0.0.2 depends on tgcalls==0.0.2
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`


Pytgcalls exist but tgcalls not...
I faced this issue...
help to slove this bro...

**Comment by xtsea** [comment]
pip3 install tgcalls

latest first

**Comment by AminSiddika** [comment]
> pip3 install -U tgcalls
> 
> latest first

https://github.com/TeamKillerX/Akeno-Userbot/issues/33#issuecomment-2301714992

**Comment by xtsea** [comment]
> ERROR: Could not find a version that satisfies the requirement tgcalls (from versions: none) ERROR: No matching distribution found for tgcalls

Type pip3 install -r -U requirements.txt again

**Comment by xtsea** [comment]
issue tgcalls

**Comment by AminSiddika** [comment]
> issue tgcalls

Again same problem

**Comment by AminSiddika** [comment]
INFO: pip is looking at multiple versions of pytgcalls to determine which version is compatible with other requirements. This could take a while.
Collecting pytgcalls (from -r requirements.txt (line 84))
  Using cached pytgcalls-2.0.0-py3-none-any.whl.metadata (11 kB)
  Using cached pytgcalls-1.0.0-py3-none-any.whl.metadata (11 kB)
  Using cached pytgcalls-0.0.24-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.23-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.22-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.21-py3-none-any.whl.metadata (10 kB)
  Using cached pytgcalls-0.0.19-py3-none-any.whl.metadata (9.6 kB)
INFO: pip is still looking at multiple versions of pytgcalls to determine which version is compatible with other requirements. This could
take a while.
  Using cached pytgcalls-0.0.18-py3-none-any.whl.metadata (9.6 kB)
  Using cached pytgcalls-0.0.17-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.16-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.15-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.14-py3-none-any.whl.metadata (8.8 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want
to abort this run, press Ctrl + C.
  Using cached pytgcalls-0.0.13-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.12-py3-none-any.whl.metadata (8.8 kB)
  Using cached pytgcalls-0.0.11-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.10-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.9-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.8-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.7-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.6-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.5-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.4-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.3-py3-none-any.whl.metadata (8.6 kB)
  Using cached pytgcalls-0.0.2-py3-none-any.whl.metadata (8.6 kB)
` WARNING: httpx 0.13.3 does not provide the extra 'http2'
: Cannot install -r requirements.txt (line 84) because these package versions have conflicting dependencies. `
The conflict is caused by:
    pytgcalls 2.1.0 depends on tgcalls==2.0.0
    pytgcalls 2.0.0 depends on tgcalls==2.0.0
    pytgcalls 1.0.0 depends on tgcalls==1.0.0
    pytgcalls 0.0.24 depends on tgcalls==0.0.16
    pytgcalls 0.0.23 depends on tgcalls==0.0.16
    pytgcalls 0.0.22 depends on tgcalls==0.0.15
    pytgcalls 0.0.21 depends on tgcalls==0.0.14
    pytgcalls 0.0.19 depends on tgcalls==0.0.12
    pytgcalls 0.0.18 depends on tgcalls==0.0.12
    pytgcalls 0.0.17 depends on tgcalls==0.0.11
    pytgcalls 0.0.16 depends on tgcalls==0.0.10
    pytgcalls 0.0.15 depends on tgcalls==0.0.10
    pytgcalls 0.0.14 depends on tgcalls==0.0.10
    pytgcalls 0.0.13 depends on tgcalls==0.0.9
    pytgcalls 0.0.12 depends on tgcalls==0.0.8
    pytgcalls 0.0.11 depends on tgcalls==0.0.7
    pytgcalls 0.0.10 depends on tgcalls==0.0.6
    pytgcalls 0.0.9 depends on tgcalls==0.0.5
    pytgcalls 0.0.8 depends on tgcalls==0.0.4
    pytgcalls 0.0.7 depends on tgcalls==0.0.4
    pytgcalls 0.0.6 depends on tgcalls==0.0.4
    pytgcalls 0.0.5 depends on tgcalls==0.0.3
    pytgcalls 0.0.4 depends on tgcalls==0.0.3
    pytgcalls 0.0.3 depends on tgcalls==0.0.3
    pytgcalls 0.0.2 depends on tgcalls==0.0.2
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by xtsea** [comment]
> INFO: pip is looking at multiple versions of pytgcalls to determine which version is compatible with other requirements. This could take a while. Collecting pytgcalls (from -r requirements.txt (line 84)) Using cached pytgcalls-2.0.0-py3-none-any.whl.metadata (11 kB) Using cached pytgcalls-1.0.0-py3-none-any.whl.metadata (11 kB) Using cached pytgcalls-0.0.24-py3-none-any.whl.metadata (10 kB) Using cached pytgcalls-0.0.23-py3-none-any.whl.metadata (10 kB) Using cached pytgcalls-0.0.22-py3-none-any.whl.metadata (10 kB) Using cached pytgcalls-0.0.21-py3-none-any.whl.metadata (10 kB) Using cached pytgcalls-0.0.19-py3-none-any.whl.metadata (9.6 kB) INFO: pip is still looking at multiple versions of pytgcalls to determine which version is compatible with other requirements. This could take a while. Using cached pytgcalls-0.0.18-py3-none-any.whl.metadata (9.6 kB) Using cached pytgcalls-0.0.17-py3-none-any.whl.metadata (8.8 kB) Using cached pytgcalls-0.0.16-py3-none-any.whl.metadata (8.8 kB) Using cached pytgcalls-0.0.15-py3-none-any.whl.metadata (8.8 kB) Using cached pytgcalls-0.0.14-py3-none-any.whl.metadata (8.8 kB) INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C. Using cached pytgcalls-0.0.13-py3-none-any.whl.metadata (8.8 kB) Using cached pytgcalls-0.0.12-py3-none-any.whl.metadata (8.8 kB) Using cached pytgcalls-0.0.11-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.10-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.9-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.8-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.7-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.6-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.5-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.4-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.3-py3-none-any.whl.metadata (8.6 kB) Using cached pytgcalls-0.0.2-py3-none-any.whl.metadata (8.6 kB) `WARNING: httpx 0.13.3 does not provide the extra 'http2' : Cannot install -r requirements.txt (line 84) because these package versions have conflicting dependencies.` The conflict is caused by: pytgcalls 2.1.0 depends on tgcalls==2.0.0 pytgcalls 2.0.0 depends on tgcalls==2.0.0 pytgcalls 1.0.0 depends on tgcalls==1.0.0 pytgcalls 0.0.24 depends on tgcalls==0.0.16 pytgcalls 0.0.23 depends on tgcalls==0.0.16 pytgcalls 0.0.22 depends on tgcalls==0.0.15 pytgcalls 0.0.21 depends on tgcalls==0.0.14 pytgcalls 0.0.19 depends on tgcalls==0.0.12 pytgcalls 0.0.18 depends on tgcalls==0.0.12 pytgcalls 0.0.17 depends on tgcalls==0.0.11 pytgcalls 0.0.16 depends on tgcalls==0.0.10 pytgcalls 0.0.15 depends on tgcalls==0.0.10 pytgcalls 0.0.14 depends on tgcalls==0.0.10 pytgcalls 0.0.13 depends on tgcalls==0.0.9 pytgcalls 0.0.12 depends on tgcalls==0.0.8 pytgcalls 0.0.11 depends on tgcalls==0.0.7 pytgcalls 0.0.10 depends on tgcalls==0.0.6 pytgcalls 0.0.9 depends on tgcalls==0.0.5 pytgcalls 0.0.8 depends on tgcalls==0.0.4 pytgcalls 0.0.7 depends on tgcalls==0.0.4 pytgcalls 0.0.6 depends on tgcalls==0.0.4 pytgcalls 0.0.5 depends on tgcalls==0.0.3 pytgcalls 0.0.4 depends on tgcalls==0.0.3 pytgcalls 0.0.3 depends on tgcalls==0.0.3 pytgcalls 0.0.2 depends on tgcalls==0.0.2 To fix this you could try to:
> 
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip to attempt to solve the dependency conflict
>    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

pip3 install -U pytgcalls==3.0.0.dev22 && pip3 uninstall Ryuzakilib -y && pip3 install git+https://github.com/TeamKillerX/RyuzakiLib

**Comment by xtsea** [comment]
Please type "git pull" update first works before install pip3 install -r requirements.txt
